<p class="bg-red-100 border-l-4 border-red-500 text-red-900 p-4 mb-6 font-medium">
    <strong>Important Notice:</strong> Crypt Me Up never holds or collects your funds. We provide simple, easy-to-use forms that let you send cryptocurrencies directly between parties. The blockchain itself acts as the trusted middleman, securely processing every transaction — we don’t interfere or handle your money at any point.
</p>

<p class="bg-yellow-100 border-l-4 border-yellow-500 text-yellow-900 p-4 mb-6 font-medium">
    <strong>Notice:</strong> This content is only available exclusively in English.
</p>

<h1 class="text-3xl font-bold text-whitemb-6"><em>Crypt Me Up</em> Terms of Service</h1>
<p class="text-base text-gray-300 mb-4">Last Updated: July 2, 2025</p>
<p class="text-lg text-white mb-4"><strong>Important</strong>: Please read these Terms of Service ("Terms") carefully. By using our website or services, you agree to follow these Terms. If you don’t agree, please do not use our website or services.</p>
<p class="text-lg text-white mb-6"><strong>Warning</strong>: Using cryptocurrencies involves risks. Their value can change rapidly, and you could lose money. Make sure you understand these risks before using our services.</p>
<p class="text-lg text-white mb-6">These Terms are a legal agreement between you ("User" or "Merchant") and <strong>Crypt Me Up</strong> ("we" or "us"), governing your use of our cryptocurrency payment processing services ("Services").</p>

<h2 class="text-2xl font-semibold text-whitemt-8 mb-4">Table of Contents</h2>
<ul class="ml-10 list-decimal text-lg text-white mb-6">
    <li>General Rules</li>
    <li>Our Services</li>
    <li>Your Responsibilities</li>
    <li>Payments and Fees</li>
    <li>Prohibited Uses</li>
    <li>Intellectual Property</li>
    <li>Liability Limits</li>
    <li>Termination</li>
    <li>Privacy</li>
    <li>Contact Us</li>
</ul>

<h2 class="text-2xl font-semibold text-whitemt-8 mb-4">1. General Rules</h2>
<ul class="ml-10 list-disc text-lg text-white mb-6">
    <li>These Terms apply to your use of our website and Services.</li>
    <li>We may update these Terms at any time. Check this page regularly for changes. Continued use means you accept any updates.</li>
    <li>You must be at least 18 years old or a registered business to use our Services.</li>
    <li>You agree to use our Services legally and comply with all applicable laws.</li>
    <li>We can modify, limit, or discontinue our Services at any time without notice.</li>
</ul>

<h2 class="text-2xl font-semibold text-whitemt-8 mb-4">2. Our Services</h2>
<p class="text-lg text-white mb-4">We offer tools to help you accept and process cryptocurrency payments, including:</p>
<ul class="ml-10 list-disc text-lg text-white mb-6">
    <li><strong>Payment Processing</strong>: Accept cryptocurrencies from your customers.</li>
    <li><strong>Payment Links</strong>: Create links for customers to pay you in crypto.</li>
</ul>

<h2 class="text-2xl font-semibold text-whitemt-8 mb-4">3. Your Responsibilities</h2>
<ul class="ml-10 list-disc text-lg text-white mb-6">
    <li><strong>Account Creation</strong>: Register with accurate details like your email and crypto wallet address. Keep your account information secure and do not share it.</li>
    <li><strong>Compliance</strong>: Follow all relevant laws, including anti-money laundering (AML) and know-your-customer (KYC) regulations.</li>
    <li><strong>Accuracy</strong>: Provide correct wallet addresses and payment details. We are not liable for losses from incorrect information.</li>
</ul>

<h2 class="text-2xl font-semibold text-whitemt-8 mb-4">4. Payments and Fees</h2>
<h3 class="text-xl font-medium text-whitemb-2">How Payments Work</h3>
<ul class="ml-10 list-disc text-lg text-white mb-4">
    <li>You create a payment request specifying the amount and currency.</li>
    <li>Customers send cryptocurrency to a unique deposit address generated by us or third-party providers.</li>
    <li>Once confirmed on the blockchain, funds are sent to your wallet or account balance.</li>
</ul>
<h3 class="text-xl font-medium text-whitemb-2">Fees</h3>
<p class="text-lg text-white mb-4">Our fees are published on our website. You are also responsible for any blockchain network fees.</p>
<h3 class="text-xl font-medium text-whitemb-2">Exchange Rates</h3>
<p class="text-lg text-white mb-4">Cryptocurrency values fluctuate. We apply the exchange rate at the time of the transaction. You accept any risks related to rate changes.</p>
<h3 class="text-xl font-medium text-whitemb-2">Taxes</h3>
<p class="text-lg text-white mb-6">You are responsible for any taxes related to your use of our Services. Please consult a tax professional for guidance.</p>

<h2 class="text-2xl font-semibold text-whitemt-8 mb-4">5. Prohibited Uses</h2>
<p class="text-lg text-white mb-4">You may not use our Services to:</p>
<ul class="ml-10 list-disc text-lg text-white mb-6">
    <li>Engage in illegal activities such as fraud, money laundering, or selling illegal goods.</li>
    <li>Distribute harmful content like viruses or obscene material.</li>
    <li>Violate others' rights including copyrights or privacy.</li>
    <li>Interfere with our Services or create competing services.</li>
</ul>
<p class="text-lg text-white mb-6">We reserve the right to suspend or terminate your account if you violate these rules.</p>

<h2 class="text-2xl font-semibold text-whitemt-8 mb-4">6. Intellectual Property</h2>
<ul class="ml-10 list-disc text-lg text-white mb-6">
    <li>We own all content, code, and designs on our website and Services.</li>
    <li>You may not copy, modify, or use our trademarks or content without permission.</li>
</ul>

<h2 class="text-2xl font-semibold text-whitemt-8 mb-4">7. Liability Limits</h2>
<ul class="ml-10 list-disc text-lg text-white mb-6">
    <li>Our Services are provided "as is" without warranties.</li>
    <li>We are not liable for losses caused by cryptocurrency value changes, third-party actions, or issues beyond our control, such as hacks or network failures.</li>
    <li>We are not responsible for indirect losses like lost profits or data loss.</li>
</ul>

<h2 class="text-2xl font-semibold text-whitemt-8 mb-4">8. Termination</h2>
<ul class="ml-10 list-disc text-lg text-white mb-6">
    <li>We may suspend or terminate your account at any time without notice if you violate these Terms or for any other reason.</li>
    <li>You may stop using our Services at any time.</li>
</ul>

<h2 class="text-2xl font-semibold text-whitemt-8 mb-4">9. Privacy</h2>
<p class="text-lg text-white mb-6">Your use of our Services is subject to our Privacy Policy, which explains how we collect, use, and protect your data.</p>

<h2 class="text-2xl font-semibold text-whitemt-8 mb-4">10. Contact Us</h2>
<p class="text-lg text-white mb-6">For questions or support, contact us via email.</p>
